## Numpy Array Operations

In [3]:
import numpy as np

In [11]:
a=np.array([1,2,3,4,5,6,7,8])
print(f"Basic Slicing{a[3:8]}")
print(f"With Step {a[2:8:2]}")
print(f"Negative Indexing {a[-3]}")

Basic Slicing[4 5 6 7 8]
With Step [3 5 7]
Negative Indexing 6


In [17]:
a_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Specific element {a_2d[1,1]}")
print(f"Entire row {a_2d[1]}")
print(f"Entire Column {a[:,2]}")

Specific element 5
Entire row [4 5 6]
Entire Column [3 6 9]


### Sorting

In [4]:
a=np.array([9,6,7,4,3,1,2])
print(f"Basic Sorting: {np.sort(a)}")

#Matrix Sorting
ar_2d=np.array([[32,51,12],[87,11,33],[96,19,57]])
print(f"Matrix Sorting Column vise: {np.sort(ar_2d,axis=0)}")
print(f"Matrix Sorting Row vise: {np.sort(ar_2d,axis=1)}")

Basic Sorting: [1 2 3 4 6 7 9]
Matrix Sorting Column vise: [[32 11 12]
 [87 19 33]
 [96 51 57]]
Matrix Sorting Row vise: [[12 32 51]
 [11 33 87]
 [19 57 96]]


### Filtering

In [4]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
even=a[a%2==0]
print(f"Even Numbers are {even}")

Even Numbers are [ 2  4  6  8 10]


### Filtering with Mask

In [15]:
mask=a%2!=0
odd=a[mask]
print(odd)

[1 3 5 7 9]


### Fancy Indexing vs np.where

In [19]:
indexes=[1,4,7]
print(f"Indexes are {a[indexes]}")

where=np.where(a>5)
print(f"Where a>5 {a[where]}")

Indexes are [2 5 8]
Where a>5 [ 6  7  8  9 10]


In [12]:
conditioned_where=np.where(a%2==0,a,a+1)
print(conditioned_where)
# Same code in JAVA
# for(i=0;i<a.length(),i++){
#      if(a[i]%2==0){
#          System.out.print(a[i])
#      }
#      else{
#          System.out.print(a[i]+1)
#      }
# }

[ 2  2  4  4  6  6  8  8 10 10]


### Adding and Removing Data

In [26]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
combine=np.concatenate((array1,array2))
print(combine)

[1 2 3 4 5 6]


### Array Compatibility

In [3]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])

print(f"Compatibility: {array1.shape==array2.shape}")

Compatibility: True


### Adding new rows & columns

In [6]:
original=np.array([[1,2],[3,4]]) 
row=np.array([[5,6]])
new_array=np.vstack((original,row))
print(new_array)

column=np.array([[2],[2]])
new_array=np.hstack((original,column))
print(new_array)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 2]
 [3 4 2]]


### Delete

In [11]:
arr=[1,2,3,4,5]
deleted=np.delete(arr,2)
print(deleted)

[1 2 4 5]
