In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [8]:
array1=np.array([1,2,3,4,5])
array2=np.random.random((3,3))*10
array3=np.zeros((4,4))

### Saving Array

In [10]:
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

### Loading array

In [15]:
loadedArray1=np.load('array1.npy')
print(f"Array1:\n{loadedArray1}")
loadedArray2=np.load('array3.npy')
print(f"Array2:\n{loadedArray2}")
loadedArray3=np.load('array3.npy')
print(f"Array3:\n{loadedArray3}")

Array1:
[1 2 3 4 5]
Array2:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array3:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
