#### Creating vitual Enviromnt
- Open Command Prompt
- python -m venv venv
- venv\Scripts\activate

# Phase 1
   

#### Arrays in Python-
   - [1,2,3,4,5]   also called vector
#### 2D Array in Python-
   - [
    [1,2,3],
    [4,5,6],
    [7,8,9]
   ]       also matrix


In [2]:
import numpy as np   #Importing numpy

### Creating array from list

In [7]:
array1d=np.array([1,2,3,4,5])  #Creating an 1D Array
print(f"1D array is {array1d}")

array2d=np.array([[1,2,3,4],[5,6,7,8]])   #Creating an 2d Array
print(f"2D Array is {array2d}") 

1D array is [1 2 3 4 5]
2D Array is [[1 2 3 4]
 [5 6 7 8]]


### List vs Numpy Array

In [4]:
list1=[1,2,3,4]
print(f"Multiplication of List is {list1*2}")

array1=np.array([1,2,3,4])
print(f"Multiplication of Array is {array1*2}")

Multiplication of List is [1, 2, 3, 4, 1, 2, 3, 4]
Multiplication of Array is [2 4 6 8]


### Creating Array for scratch

In [9]:
zeros=np.zeros((4,4))   #Creates a matrix of 0s
print("Matrix of Zeros")
print(zeros)

Matrix of Zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones=np.ones((3,3))   #Creates a matrix of 1s
print("Matrix of Ones")
print(ones)

Matrix of Znes
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
full=np.full((2,2),6)  #Creates a matrix of a Constant
print("Matrix of Constant")
print(full)

Matrix of Constant
[[6 6]
 [6 6]]


In [12]:
full=np.full((2,2),6)  #Creates a matrix of a Constant
print("Matrix of Constant")
print(full)

Matrix of Constant
[[6 6]
 [6 6]]


In [13]:
randomMatrix=np.random.random((3,3))*10   #Creates an matrix of random values
print("Matrix of random values")
print(randomMatrix)

Matrix of random values
[[7.09468806 8.10011126 4.01105124]
 [6.52787599 2.13736319 2.2131554 ]
 [8.48384492 1.66277425 4.13723216]]


In [14]:
sequence=np.arange(1,30,3)  #Creates an array of series with gap of 3
print("Array of aequence")
print(sequence)

Array of aequence
[ 1  4  7 10 13 16 19 22 25 28]


### Vector,Matrix & Tensor

In [16]:
vector=np.array([1,2,3,4,5])
print(f"Vector is: {vector}")

matrix=np.array([[4,5,6],[1,2,3]])
print(f"Matrix is: {matrix}")

tensor=np.array([[[2,4],[8,9]],[[5,6],[3,3]]])
print(f"Tensor is: {tensor}")

Vector is: [1 2 3 4 5]
Matrix is: [[4 5 6]
 [1 2 3]]
Tensor is: [[[2 4]
  [8 9]]

 [[5 6]
  [3 3]]]


### Array Properties

In [19]:
a=np.array([[[3,3],[2,2]],[[4,4],[7,7]]])
print(f"Shape {a.shape}")
print(f"Dimension {a.ndim}")
print(f"Size {a.size}")
print(f"Datatype {a.dtype}")

Shape (2, 2, 2)
Dimension 3
Size 8
Datatype int64


### Array Reshaping

In [3]:
a=np.arange(15)
print(f"Array is {a}")

reshape=a.reshape((-3,5))
print(f"Reshaped array is: {reshape}")

flatened=reshape.flatten()
print(f"Flattened array is {flatened}")

ravled=reshape.ravel() #returns the original array
print(f"Raveled array is {ravled}")

transpose=reshape.T
print(f"Transpose array is {transpose}")





Array is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reshaped array is: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Flattened array is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Raveled array is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Transpose array is [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
